DATASETS_DIR = "datasets"
DATASET_GZ_NAME = "sx-stackoverflow.txt.gz"
DATASET_NAME = "sx-stackoverflow.txt"
DATASET_URL = "https://snap.stanford.edu/data/sx-stackoverflow.txt.gz"
DFCOL_SRC = "SRC"
DFCOL_DST = "DST"
DFCOL_UNIXTS = "UNIXTS"
DFCOLS = [DFCOL_SRC, DFCOL_DST, DFCOL_UNIXTS]
N = 3000
N_SHOW_NODES_EDGES = 4
N_SHOW_HISTOGRAMS = 2
OUTPUT_DIR = "output"
CACHE_DIR = "cache"
USE_CACHE_INTRO = True
USE_CACHE_PART1 = False
USE_CACHE_PART1_DATA = True
SHOULD_PLOT_GRAPH = False
