DATASETS_DIR = "datasets"
DATASET_GZ_NAME = "sx-stackoverflow.txt.gz"
DATASET_NAME = "sx-stackoverflow.txt"
DATASET_URL = "https://snap.stanford.edu/data/sx-stackoverflow.txt.gz"
DFCOL_SRC = "SRC"
DFCOL_DST = "DST"
DFCOL_UNIXTS = "UNIXTS"
DFCOLS = [DFCOL_SRC, DFCOL_DST, DFCOL_UNIXTS]
N = 20000
SHOW_N = 6
OUTPUT_DIR = "output"
CACHE_DIR = "cache"
USE_CACHE_INTRO = True
